### ISSUE TITLE
Error after click 'go' button

### ISSUE THREAD

**Issue by ranistar** [NicolasPrats/DvBrowser#2]
**Error info:**
Could not find a part of the path 'C:\Users\someone\AppData\Local\Dataverse.Browser\config.json'

**Error screenshot:**
![image](https://user-images.githubusercontent.com/14199700/231115939-9c6fbdb5-cb25-47c8-aeb7-0dac36914257.png)

**Full stack trace:**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\someone\AppData\Local\Dataverse.Browser\config.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Dataverse.Browser.Configuration.ConfigurationManager.SaveConfiguration(DataverseBrowserConfiguration config) in C:\Users\nicolas.prats\source\repos\CrmBrowser\Dataverse.Browser\Configuration\ConfigurationManager.cs:line 33
   at Dataverse.Browser.UI.EnvironmentPicker.Pick(EnvironnementConfiguration environment) in C:\Users\nicolas.prats\source\repos\CrmBrowser\Dataverse.Browser\UI\EnvironmentPicker.cs:line 69
   at Dataverse.Browser.UI.EnvironmentPicker.EnvironmentPicker_Load(Object sender, EventArgs e) in C:\Users\nicolas.prats\source\repos\CrmBrowser\Dataverse.Browser\UI\EnvironmentPicker.cs:line 45
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Dataverse.Browser
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/someone/Downloads/DataverseBrowser/Dataverse.Browser.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.150
    CodeBase: file:///C:/Users/someone/Downloads/DataverseBrowser/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Dataverse.Plugin.Emulator
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/someone/Downloads/DataverseBrowser/Dataverse.Plugin.Emulator.DLL
----------------------------------------
System.Text.Json
    Assembly Version: 7.0.0.2
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/someone/Downloads/DataverseBrowser/System.Text.Json.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Users/someone/Downloads/DataverseBrowser/Microsoft.Bcl.AsyncInterfaces.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.2
    Win32 Version: 4.6.31308.01
    CodeBase: file:///C:/Users/someone/Downloads/DataverseBrowser/System.Memory.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Users/someone/Downloads/DataverseBrowser/System.Text.Encodings.Web.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Users/someone/Downloads/DataverseBrowser/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/someone/Downloads/DataverseBrowser/System.Threading.Tasks.Extensions.DLL
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/someone/Downloads/DataverseBrowser/System.Buffers.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by NicolasPrats** [comment]
Hi @ranistar ,

Thank you for having opened this ticket. This bug is fixed in [the new release](https://github.com/NicolasPrats/DvBrowser/releases).
